/**
 * ============================================================================
 * MAP DATA  -  generated by the map editor
 * ============================================================================
 * Drop this file into src/world/ , replacing the existing mapData.js.
 * Everything else (bridge maths, roads, validation) lives in
 * islandLayout.js and does not need changing.
 *
 * To keep editing later: paste this whole file back into the editor's
 * Import box.
 * ============================================================================
 *
 * LAYOUT NOTES  -  redesign, 29 July 2026
 *
 * Hub and spoke, spread out and scaled up. The bearings are roughly where
 * they were, so the world still reads the same way from the hub, but
 * everything sits about twice as far out and the islands are bigger.
 *
 * The islands are big AND well separated, which is why the car is faster
 * than it used to be. Every crossing is about 130 units of open water -
 * long enough that the sea reads as sea rather than a moat, and at 18
 * units/sec that's roughly seven seconds, which is a journey rather than
 * a chore. Distances were solved backwards from that target span, which
 * is why they aren't round numbers.
 *
 * Sizes are deliberately uneven. EXPERIENCE is the largest because it
 * carries the most content; BLOG is the smallest. Six islands of the same
 * size read as a menu rather than a place.
 *
 * Shapes vary too. They were all 'blob' before, which made every island -
 * and every ring road on it - look like the last one. Change any `shape`
 * back to 'blob' if you preferred it.
 */

export const ISLANDS = [
  {
    id: 'hub',
    x: 0,
    z: 0,
    radius: 80,
    theme: 'plain',
    accent: 0xffffff,
    name: '',
    palms: 14,
    shape: 'blob',
    shapeSeed: 12,
    districts: [
      { type: 'plaza', x: 0, z: 0, size: 34 }
    ],
    // Deliberately gentle to begin with. See "Hills" in MAP.md: the roads and
    // the building pads flatten themselves out of whatever you put here, so
    // the thing to watch when you raise these is the SLOPE between them.
    hills: [
      { x: -34, z: 30, radius: 42, height: 3 },
      { x: 40, z: -22, radius: 38, height: 2.5 }
    ]
  },
  {
    id: 'about',
    x: 33.8,
    z: 244.2,
    radius: 88,
    theme: 'town',
    accent: 0x4facfe,
    name: 'ABOUT',
    palms: 10,
    shape: 'wide',
    shapeSeed: 4,
    hills: [
      { x: -40, z: -18, radius: 50, height: 4.5 },
      { x: 46, z: 34, radius: 44, height: 3 }
    ]
  },
  {
    id: 'projects',
    x: 270.3,
    z: 36.5,
    radius: 100,
    theme: 'town',
    accent: 0x00f2fe,
    name: 'EXPERIENCE',
    palms: 10,
    shape: 'long',
    shapeSeed: 9,
    hills: [
      { x: 10, z: -46, radius: 52, height: 5 },
      { x: -20, z: 40, radius: 46, height: 3.5 }
    ]
  },
  {
    id: 'skills',
    x: 201.2,
    z: -203.8,
    radius: 79,
    theme: 'jungle',
    accent: 0xa855f7,
    name: 'SKILLS',
    palms: 14,
    shape: 'crescent',
    shapeSeed: 3,
    hills: [
      { x: 0, z: 0, radius: 55, height: 6 }
    ]
  },
  {
    id: 'blog',
    x: -169.9,
    z: -231.8,
    radius: 70,
    theme: 'jungle',
    accent: 0xfbbf24,
    name: 'BLOG',
    palms: 12,
    shape: 'blob',
    shapeSeed: 21,
    hills: [
      { x: 18, z: 14, radius: 46, height: 5.5 }
    ]
  },
  {
    id: 'contact',
    x: -261.4,
    z: 65.6,
    radius: 84,
    theme: 'mixed',
    accent: 0xf472b6,
    name: 'CONTACT',
    palms: 12,
    shape: 'triangle',
    shapeSeed: 6,
    hills: [
      { x: -26, z: -26, radius: 48, height: 4 },
      { x: 34, z: 24, radius: 40, height: 2.5 }
    ]
  }
]

export const BRIDGES = [
  { from: 'hub', to: 'about' },
  { from: 'hub', to: 'projects' },
  { from: 'hub', to: 'skills' },
  { from: 'hub', to: 'blog' },
  { from: 'hub', to: 'contact' }
]
