/**
 * ============================================================================
 * MAP DATA  -  generated by the map editor
 * ============================================================================
 * Drop this file into src/world/ , replacing the existing mapData.js.
 * Everything else (bridge maths, roads, validation) lives in
 * islandLayout.js and does not need changing.
 *
 * To keep editing later: paste this whole file back into the editor's
 * Import box.
 * ============================================================================
 */

export const ISLANDS = [
  {
    id: 'hub',
    x: 0,
    z: 0,
    radius: 24,
    theme: 'plain',
    accent: 0xffffff,
    name: '',
    palms: 12,
    shape: 'blob',
    shapeSeed: 12,
    districts: [
      { type: 'plaza', x: 0, z: 0, size: 19 }
    ]
  },
  {
    id: 'about',
    x: 0,
    z: 62,
    radius: 20,
    theme: 'town',
    accent: 0x4facfe,
    name: 'ABOUT',
    shape: 'blob',
    shapeSeed: 4
  },
  {
    id: 'projects',
    x: 59,
    z: 19.2,
    radius: 22,
    theme: 'town',
    accent: 0x00f2fe,
    name: 'EXPERIENCE',
    shape: 'wide',
    shapeSeed: 9
  },
  {
    id: 'skills',
    x: 36.4,
    z: -50.2,
    radius: 20,
    theme: 'jungle',
    accent: 0xa855f7,
    name: 'SKILLS',
    palms: 10,
    shape: 'crescent',
    shapeSeed: 3
  },
  {
    id: 'blog',
    x: -36.4,
    z: -50.2,
    radius: 18,
    theme: 'jungle',
    accent: 0xfbbf24,
    name: 'BLOG',
    palms: 10,
    shape: 'blob',
    shapeSeed: 21,
    buildings: [
      { x: -3.4, z: 9.6, rotation: 110, model: 'building_a' },
      { x: -5.5, z: 3.7, rotation: 109, model: 'building_b' }
    ]
  },
  {
    id: 'contact',
    x: -59,
    z: 19.2,
    radius: 19,
    theme: 'mixed',
    accent: 0xf472b6,
    name: 'CONTACT',
    shape: 'long',
    shapeSeed: 6
  }
]

export const BRIDGES = [
  { from: 'hub', to: 'about' },
  { from: 'hub', to: 'projects' },
  { from: 'hub', to: 'skills' },
  { from: 'hub', to: 'blog' },
  { from: 'hub', to: 'contact' }
]
