/**
 * ============================================================================
 * MAP DATA  -  generated by the map editor
 * ============================================================================
 * Drop this file into src/world/ , replacing the existing mapData.js.
 * Everything else (bridge maths, roads, validation) lives in
 * islandLayout.js and does not need changing.
 *
 * To keep editing later: paste this whole file back into the editor's
 * Import box.
 * ============================================================================
 */

export const ISLANDS = [
  {
    id: 'hub',
    x: 0,
    z: 0,
    radius: 24,
    theme: 'plain',
    accent: 0xffffff,
    name: '',
    palms: 12,
    shape: 'blob',
    shapeSeed: 12,
    districts: [
      { type: 'plaza', x: 0, z: 0, size: 19 }
    ]
  },
  {
    id: 'about',
    x: 3.3,
    z: 70.3,
    radius: 40,
    theme: 'town',
    accent: 0x4facfe,
    name: 'ABOUT',
    shape: 'blob',
    shapeSeed: 4
  },
  {
    id: 'projects',
    x: 96,
    z: 11.8,
    radius: 39,
    theme: 'town',
    accent: 0x00f2fe,
    name: 'EXPERIENCE',
    shape: 'blob',
    shapeSeed: 9
  },
  {
    id: 'skills',
    x: 62.9,
    z: -62.7,
    radius: 36,
    theme: 'jungle',
    accent: 0xa855f7,
    name: 'SKILLS',
    palms: 10,
    shape: 'blob',
    shapeSeed: 3
  },
  {
    id: 'blog',
    x: -48.9,
    z: -63.7,
    radius: 42,
    theme: 'jungle',
    accent: 0xfbbf24,
    name: 'BLOG',
    palms: 10,
    shape: 'blob',
    shapeSeed: 21
  },
  {
    id: 'contact',
    x: -85.3,
    z: 25.1,
    radius: 38,
    theme: 'mixed',
    accent: 0xf472b6,
    name: 'CONTACT',
    shape: 'blob',
    shapeSeed: 6
  }
]

export const BRIDGES = [
  { from: 'hub', to: 'about' },
  { from: 'hub', to: 'projects' },
  { from: 'hub', to: 'skills' },
  { from: 'hub', to: 'blog' },
  { from: 'hub', to: 'contact' }
]
